"""
Django settings for doctor project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
from decouple import config, Csv
import logging
logger = logging.getLogger(__name__)


load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS').split(',')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "drf_yasg",
    "djoser",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "account",
    "management",
    'import_export',
    'django_filters',

]



# Redis with django-redis (pip install django-redis)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
        'LOCATION': '127.0.0.1:11211',
        'OPTIONS': {
            'no_delay': True,
            'ignore_exc': True,
        },
        'KEY_PREFIX': 'medical_api',
        'TIMEOUT': 3600,  # 1 hour
        'VERSION': 1,
    },
    'sessions': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/2',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'PASSWORD': os.environ.get('REDIS_PASSWORD', None),
        },
        'KEY_PREFIX': 'session',
        'TIMEOUT': 7200,  # 2 hours
    },
    'quick': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'quick-cache',
        'TIMEOUT': 300,  # 5 minutes
        'OPTIONS': {
            'MAX_ENTRIES': 2000,
            'CULL_FREQUENCY': 3,
        },
    },
}
# ============================================================================
# OPTION 2: MEMCACHED CONFIGURATION
# ============================================================================

# Memcached with python-memcached (pip install python-memcached)
CACHES_MEMCACHED = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
        'LOCATION': [
            '127.0.0.1:11211',
            # '127.0.0.1:11212',  # Multiple servers for redundancy
        ],
        'OPTIONS': {
            'server_max_value_length': 1024 * 1024 * 10,  # 10MB max value
        },
        'KEY_PREFIX': 'medical_data',
        'TIMEOUT': 900,
        'VERSION': 1,
    }
}

# ============================================================================
# OPTION 3: MULTI-TIER CACHING (Best Performance)
# ============================================================================

CACHES_MULTI_TIER = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {'max_connections': 20},
        },
        'KEY_PREFIX': 'medical_primary',
        'TIMEOUT': 900,
    },
    'quick': {
        # In-memory cache for frequently accessed small data
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'quick-cache',
        'TIMEOUT': 300,  # 5 minutes
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    },
    'persistent': {
        # Database cache for data that needs persistence
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_table',
        'TIMEOUT': 3600 * 24,  # 24 hours
    }
}

# ============================================================================
# CACHE MIDDLEWARE CONFIGURATION
# ============================================================================


MIDDLEWARE = [
    'django.middleware.cache.UpdateCacheMiddleware',  # Must be first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',  # Must be last

]

ROOT_URLCONF = 'doctor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'doctor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get('POSTGRES_ENGINE', "django.contrib.gis.db.backends.postgis"),
        "NAME": os.environ.get('POSTGRES_NAME'),
        "USER": os.environ.get('POSTGRES_USER'),
        "PASSWORD": os.environ.get('POSTGRES_PASSWORD'),
        "HOST": os.environ.get('POSTGRES_HOST', "localhost"),
        "PORT": os.environ.get('POSTGRES_PORT', "5432"),
        "ATOMIC_MUTATIONS": True,
        "DISABLE_SERVER_SIDE_CURSORS": True,
    }
}


POSTGRES_ENGINE= os.environ.get('POSTGRES_ENGINE', "django.contrib.gis.db.backends.postgis"),
POSTGRES_NAME= os.environ.get('POSTGRES_NAME'),
POSTGRES_USER= os.environ.get('POSTGRES_USER'),
POSTGRES_PASSWORD= os.environ.get('POSTGRES_PASSWORD'),
POSTGRES_HOST= os.environ.get('POSTGRES_HOST', "localhost"),
POSTGRES_PORT= os.environ.get('POSTGRES_PORT', 5432),


# Cache middleware settings
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 600  # 10 minutes
CACHE_MIDDLEWARE_KEY_PREFIX = 'page_cache'

# ============================================================================
# SESSION CONFIGURATION
# ============================================================================

# Use Redis for sessions (if using Redis)
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'sessions'  # or 'default' if single cache
SESSION_COOKIE_AGE = 3600  # 1 hour

# ============================================================================
# OPTIMIZED API VIEW WITH MULTI-CACHE STRATEGY
# =====================================================


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

if DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')


MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = "account.User"

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    #
    # 'DEFAULT_RENDERER_CLASSES': (
    #     # 'rest_framework.renderers.BrowsableAPIRenderer',
    #     # 'rest_framework.renderers.JSONRenderer',
    # ),

    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),

    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        'rest_framework.authentication.SessionAuthentication',
    ),

    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_SCHEMA_CLASS': 'rest_framework_gis.schema.GeoFeatureAutoSchema',
}

SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("JWT",),
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=1440),
    'REFRESH_TOKEN_LIFETIME': timedelta(minutes=1440),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}

SITE_ID = 1
# DJOSER CONFIG
DJOSER = {
    "LOGIN_FIELD": "email",
    'USER_ID_FIELD': 'id',
    # "USER_CREATE_PASSWORD_RETYPE": True,
    "USERNAME_CHANGED_EMAIL_CONFIRMATION": True,
    "PASSWORD_CHANGED_EMAIL_CONFIRMATION": True,
    "SEND_CONFIRMATION_EMAIL": True,
    "SET_USERNAME_RETYPE": True,
    "SET_PASSWORD_RETYPE": True,
    "USERNAME_RESET_CONFIRM_URL": "email/reset/confirm/{uid}/{token}",
    "PASSWORD_RESET_CONFIRM_URL": "forget/password/confirm/{uid}/{token}",
    'ACTIVATION_URL': 'activation/{uid}/{token}',
    "SEND_ACTIVATION_EMAIL": True,
    'TOKEN_MODEL': None,
    "SERIALIZERS": {
        "user_create": "account.serializer.UserCreateSerializer",  # custom serializer
        "user": "djoser.serializers.UserSerializer",
        "current_user": "djoser.serializers.UserSerializer",
        "user_delete": "djoser.serializers.UserSerializer",

    },
    'EMAIL': {
        'activation': 'account.email.ActivationEmail',
        'confirmation': 'account.email.ConfirmationEmail',
        'password_reset': 'account.email.PasswordResetEmail',
        'password_changed_confirmation': 'account.email.PasswordChangedConfirmationEmail',
    },
}



ALLOWED_ORIGINS = os.environ.get('ALLOWED_ORIGINS').split(',')

CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', cast=bool)
CORS_ORIGIN_ALLOW_ALL = config('CORS_ORIGIN_ALLOW_ALL', cast=bool)
CORS_ALLOW_CREDENTIALS = config('CORS_ALLOW_CREDENTIALS', cast=bool)
CORS_ALLOW_ALL_HEADERS = config('CORS_ALLOW_ALL_HEADERS', cast=bool)
CORS_ORIGIN_WHITELIST = os.environ.get('CORS_ORIGIN_WHITELIST').split(',')
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS').split(',')
CORS_ALLOW_ALL_SUBDOMAINS = config('CORS_ALLOW_ALL_SUBDOMAINS', cast=bool)
CORS_ALLOW_WILDCARD = config('CORS_ALLOW_WILDCARD', cast=bool)

CORS_URLS_REGEX = r"^/api/.*$"
CORS_ALLOWED_ORIGIN_REGEXES = [r"^https://\w+.dirhamperfoot.ae", ]
CORS_ALLOWED_HOSTS = ['https://dirhamperfoot.com']
CORS_ALLOWED_HEADERS = ['Authorization', 'Content-Type']

CORS_EXPOSE_HEADERS = [
    'Set-Cookie',
    # 'X-Custom-Header',
]
CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'DELETE',
    'OPTIONS',
    'PATCH',
]

CORS_ALLOW_HEADERS = [
    'Authorization',
    'Content-Type',
    'Custom-Header',
]